import type { Lang } from "./i18n";

export const ui = {
  ru: {
    parishName: "Греко-католический приход",
    city: "Алматы",
    navToday: "Сегодня",
    navNews: "Новости",
    navScripture: "Писание",
    navTelegram: "Телеграм",
    navHistory: "История",
    openCalendar: "Литургический календарь",
    closeModal: "Закрыть",
    newsFilters: "Фильтры",
    todayFeast: "Сегодня в календаре",
    noFeast: "Сегодня нет особого праздника по выбранным данным.",
    prayer: "Молитва",
    newsTitle: "Новости прихода",
    filterKeyword: "Ключевые слова",
    filterFrom: "С даты",
    filterTo: "По дату",
    resetFilters: "Сбросить",
    noNews: "Новостей пока нет.",
    calendarTitle: "Литургический календарь",
    calendarHint: "Нажмите на день или событие, чтобы прочитать пояснение.",
    scriptureTitle: "Священное Писание",
    scriptureHint: "Чтение онлайн и скачивание на выбранном языке.",
    readOnline: "Читать онлайн",
    download: "Скачать",
    notAvailableLang: "Для этого языка файл пока не добавлен.",
    scriptureEditionMain: "Основная версия",
    scripturePickLanguage: "Выберите язык версии",
    scriptureNoLinkForEdition: "Нет ссылки для этой версии",
    scripturePrimaryBadge: "основная версия",
    scripturePrimaryOnSite: "Основная версия на сайте",
    scripturePrimaryLegacyNote:
      "Укажите язык основной версии в админке: откройте книгу и выберите язык в поле «Язык основной версии».",
    langNativeRu: "Русский",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "English",
    telegramTitle: "Сообщения из Telegram",
    telegramEmpty: "Сообщений пока нет. Подключите бота к группе и вебхук.",
    contacts: "Контакты",
    address: "Адрес",
    historyPageTitle: "История Церкви",
    expandNews: "Развернуть",
    collapseNews: "Свернуть",
  },
  uk: {
    parishName: "Греко-католицька парафія",
    city: "Алмати",
    navToday: "Сьогодні",
    navNews: "Новини",
    navScripture: "Писання",
    navTelegram: "Telegram",
    navHistory: "Історія",
    openCalendar: "Літургійний календар",
    closeModal: "Закрити",
    newsFilters: "Фільтри",
    todayFeast: "Сьогодні в календарі",
    noFeast: "Сьогодні немає особливого свята за наявними даними.",
    prayer: "Молитва",
    newsTitle: "Новини парафії",
    filterKeyword: "Ключові слова",
    filterFrom: "Від дати",
    filterTo: "До дати",
    resetFilters: "Скинути",
    noNews: "Новин ще немає.",
    calendarTitle: "Літургійний календар",
    calendarHint: "Натисніть на день або подію, щоб прочитати пояснення.",
    scriptureTitle: "Святе Письмо",
    scriptureHint: "Читання онлайн і завантаження обраною мовою.",
    readOnline: "Читати онлайн",
    download: "Завантажити",
    notAvailableLang: "Для цієї мови файл ще не додано.",
    scriptureEditionMain: "Основна версія",
    scripturePickLanguage: "Оберіть мову версії",
    scriptureNoLinkForEdition: "Немає посилання для цієї версії",
    scripturePrimaryBadge: "основна версія",
    scripturePrimaryOnSite: "Основна версія на сайті",
    scripturePrimaryLegacyNote:
      "Вкажіть мову основної версії в адмінці: відкрийте книгу та оберіть мову в полі «Мова основної версії».",
    langNativeRu: "Російська",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "Англійська",
    telegramTitle: "Повідомлення з Telegram",
    telegramEmpty: "Повідомлень ще немає.",
    contacts: "Контакти",
    address: "Адреса",
    historyPageTitle: "Історія Церкви",
    expandNews: "Розгорнути",
    collapseNews: "Згорнути",
  },
  kk: {
    parishName: "Грек-католик қауымы",
    city: "Алматы",
    navToday: "Бүгін",
    navNews: "Жаңалықтар",
    navScripture: "Қасиетті жазба",
    navTelegram: "Telegram",
    navHistory: "Тарих",
    openCalendar: "Литургиялық күнтізбе",
    closeModal: "Жабу",
    newsFilters: "Сүзгілер",
    todayFeast: "Бүгін күнтізбеде",
    noFeast: "Бүгін ерекше мереке жоқ.",
    prayer: "Дұға",
    newsTitle: "Қауым жаңалықтары",
    filterKeyword: "Кілт сөздер",
    filterFrom: "Бастап",
    filterTo: "Дейін",
    resetFilters: "Тазалау",
    noNews: "Жаңалық жоқ.",
    calendarTitle: "Литургиялық күнтізбе",
    calendarHint: "Түсіндірме үшін күнге немесе оқиғаға басыңыз.",
    scriptureTitle: "Қасиетті жазба",
    scriptureHint: "Таңдалған тілде оқу және жүктеу.",
    readOnline: "Онлайн оқу",
    download: "Жүктеу",
    notAvailableLang: "Бұл тілде әлі файл жоқ.",
    scriptureEditionMain: "Негізгі нұсқа",
    scripturePickLanguage: "Нұсқа тілін таңдаңыз",
    scriptureNoLinkForEdition: "Бұл нұсқа үшін сілтеме жоқ",
    scripturePrimaryBadge: "негізгі нұсқа",
    scripturePrimaryOnSite: "Сайттағы негізгі нұсқа",
    scripturePrimaryLegacyNote:
      "Негізгі нұсқаның тілін әкімшілікте көрсетіңіз: кітапты ашып, «Негізгі нұсқа тілі» өрісін толтырыңыз.",
    langNativeRu: "Орысша",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "Ағылшын",
    telegramTitle: "Telegram хабарламалары",
    telegramEmpty: "Хабарламалар әлі жоқ.",
    contacts: "Байланыс",
    address: "Мекенжай",
    historyPageTitle: "Шіркеу тарихы",
    expandNews: "Толығырақ",
    collapseNews: "Жию",
  },
  en: {
    parishName: "Greek Catholic parish",
    city: "Almaty",
    navToday: "Today",
    navNews: "News",
    navScripture: "Scripture",
    navTelegram: "Telegram",
    navHistory: "History",
    openCalendar: "Liturgical calendar",
    closeModal: "Close",
    newsFilters: "Filters",
    todayFeast: "Today in the calendar",
    noFeast: "There is no major feast listed for today.",
    prayer: "Prayer",
    newsTitle: "Parish news",
    filterKeyword: "Keywords",
    filterFrom: "From",
    filterTo: "To",
    resetFilters: "Reset",
    noNews: "No news yet.",
    calendarTitle: "Liturgical calendar",
    calendarHint: "Click a day or event to read details and rules.",
    scriptureTitle: "Holy Scripture",
    scriptureHint: "Read online or download in your language.",
    readOnline: "Read online",
    download: "Download",
    notAvailableLang: "No file for this language yet.",
    scriptureEditionMain: "Default edition",
    scripturePickLanguage: "Choose edition language",
    scriptureNoLinkForEdition: "No link for this edition",
    scripturePrimaryBadge: "primary edition",
    scripturePrimaryOnSite: "Primary edition on the site",
    scripturePrimaryLegacyNote:
      "Set the primary edition language in the admin: open the book and use the “Primary language” field.",
    langNativeRu: "Russian",
    langNativeUk: "Ukrainian",
    langNativeKk: "Kazakh",
    langNativeEn: "English",
    telegramTitle: "Telegram messages",
    telegramEmpty: "No messages yet.",
    contacts: "Contacts",
    address: "Address",
    historyPageTitle: "Church history",
    expandNews: "Read more",
    collapseNews: "Show less",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type UiKey = keyof (typeof ui)["ru"];

export function t(lang: Lang, key: UiKey): string {
  return ui[lang][key] ?? ui.ru[key];
}
