import type { Lang } from "./i18n";

export const ui = {
  ru: {
    parishName: "Греко-католический приход",
    city: "Алматы",
    navHome: "Главная",
    navNews: "Новости",
    navLibrary: "Библиотека",
    navTelegram: "Телеграм",
    navHistory: "История",
    openCalendar: "Литургический календарь",
    closeModal: "Закрыть",
    imageLightboxAria: "Просмотр изображения",
    newsFilters: "Фильтры",
    todayFeast: "Календарь",
    noFeast: "Сегодня нет особого праздника по выбранным данным.",
    prayer: "Молитва",
    newsTitle: "Новости прихода",
    filterKeyword: "Ключевые слова",
    filterFrom: "С даты",
    filterTo: "По дату",
    resetFilters: "Сбросить",
    noNews: "Новостей пока нет.",
    calendarTitle: "Литургический календарь",
    calendarHint: "Нажмите на день или событие, чтобы прочитать пояснение.",
    scriptureTitle: "Полезные книги",
    scriptureHint: "Читайте онлайн и скачивайте на выбранном языке.",
    moreDetails: "Подробнее",
    paginationPrev: "Назад",
    paginationNext: "Вперёд",
    paginationPageOf: "Стр. {n} из {m}",
    calendarPrevMonth: "Предыдущий месяц",
    calendarNextMonth: "Следующий месяц",
    libraryPageTitle: "Библиотека",
    libraryFiltersSection: "Фильтры и сортировка",
    libraryFiltersToggleAria: "Фильтры и сортировка",
    librarySortDate: "По дате загрузки",
    librarySortAlpha: "По алфавиту",
    librarySortLabel: "Сортировка",
    libraryFilterKeyword: "Ключевые слова",
    libraryFilterFrom: "Загружено с",
    libraryFilterTo: "Загружено по",
    librarySubmit: "Применить",
    libraryEmpty: "Нет книг по заданным условиям.",
    readOnline: "Читать онлайн",
    download: "Скачать",
    notAvailableLang: "Для этого языка файл пока не добавлен.",
    scriptureEditionMain: "Основная версия",
    scripturePickLanguage: "Выберите язык версии",
    scriptureNoLinkForEdition: "Нет ссылки для этой версии",
    scripturePrimaryBadge: "основная версия",
    scripturePrimaryOnSite: "Основная версия на сайте",
    scripturePrimaryLegacyNote:
      "Укажите язык основной версии в админке: откройте книгу и выберите язык в поле «Язык основной версии».",
    langNativeRu: "Русский",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "English",
    telegramTitle: "Сообщения из Telegram",
    telegramEmpty: "Сообщений пока нет. Подключите бота к группе и вебхук.",
    contacts: "Контакты",
    address: "Адрес",
    historyPageTitle: "История Церкви",
    openNews: "Открыть новость",
    siteLangSelectAria: "Язык сайта",
  },
  uk: {
    parishName: "Греко-католицька парафія",
    city: "Алмати",
    navHome: "Головна",
    navNews: "Новини",
    navLibrary: "Бібліотека",
    navTelegram: "Telegram",
    navHistory: "Історія",
    openCalendar: "Літургійний календар",
    closeModal: "Закрити",
    imageLightboxAria: "Перегляд зображення",
    newsFilters: "Фільтри",
    todayFeast: "Календар",
    noFeast: "Сьогодні немає особливого свята за наявними даними.",
    prayer: "Молитва",
    newsTitle: "Новини парафії",
    filterKeyword: "Ключові слова",
    filterFrom: "Від дати",
    filterTo: "До дати",
    resetFilters: "Скинути",
    noNews: "Новин ще немає.",
    calendarTitle: "Літургійний календар",
    calendarHint: "Натисніть на день або подію, щоб прочитати пояснення.",
    scriptureTitle: "Корисні книги",
    scriptureHint: "Читайте онлайн і завантажуйте обраною мовою.",
    moreDetails: "Докладніше",
    paginationPrev: "Назад",
    paginationNext: "Далі",
    paginationPageOf: "Стор. {n} з {m}",
    calendarPrevMonth: "Попередній місяць",
    calendarNextMonth: "Наступний місяць",
    libraryPageTitle: "Бібліотека",
    libraryFiltersSection: "Фільтри та сортування",
    libraryFiltersToggleAria: "Фільтри та сортування",
    librarySortDate: "За датою завантаження",
    librarySortAlpha: "За абеткою",
    librarySortLabel: "Сортування",
    libraryFilterKeyword: "Ключові слова",
    libraryFilterFrom: "Завантажено від",
    libraryFilterTo: "Завантажено до",
    librarySubmit: "Застосувати",
    libraryEmpty: "Немає книг за цими умовами.",
    readOnline: "Читати онлайн",
    download: "Завантажити",
    notAvailableLang: "Для цієї мови файл ще не додано.",
    scriptureEditionMain: "Основна версія",
    scripturePickLanguage: "Оберіть мову версії",
    scriptureNoLinkForEdition: "Немає посилання для цієї версії",
    scripturePrimaryBadge: "основна версія",
    scripturePrimaryOnSite: "Основна версія на сайті",
    scripturePrimaryLegacyNote:
      "Вкажіть мову основної версії в адмінці: відкрийте книгу та оберіть мову в полі «Мова основної версії».",
    langNativeRu: "Російська",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "Англійська",
    telegramTitle: "Повідомлення з Telegram",
    telegramEmpty: "Повідомлень ще немає.",
    contacts: "Контакти",
    address: "Адреса",
    historyPageTitle: "Історія Церкви",
    openNews: "Відкрити новину",
    siteLangSelectAria: "Мова сайту",
  },
  kk: {
    parishName: "Грек-католик қауымы",
    city: "Алматы",
    navHome: "Басты бет",
    navNews: "Жаңалықтар",
    navLibrary: "Кітапхана",
    navTelegram: "Telegram",
    navHistory: "Тарих",
    openCalendar: "Литургиялық күнтізбе",
    closeModal: "Жабу",
    imageLightboxAria: "Суретті көру",
    newsFilters: "Сүзгілер",
    todayFeast: "Күнтізбе",
    noFeast: "Бүгін ерекше мереке жоқ.",
    prayer: "Дұға",
    newsTitle: "Қауым жаңалықтары",
    filterKeyword: "Кілт сөздер",
    filterFrom: "Бастап",
    filterTo: "Дейін",
    resetFilters: "Тазалау",
    noNews: "Жаңалық жоқ.",
    calendarTitle: "Литургиялық күнтізбе",
    calendarHint: "Түсіндірме үшін күнге немесе оқиғаға басыңыз.",
    scriptureTitle: "Пайдалы кітаптар",
    scriptureHint: "Онлайн оқыңыз және таңдалған тілде жүктеп алыңыз.",
    moreDetails: "Толығырақ",
    paginationPrev: "Артқа",
    paginationNext: "Алға",
    paginationPageOf: "Бет {n} / {m}",
    calendarPrevMonth: "Алдыңғы ай",
    calendarNextMonth: "Келесі ай",
    libraryPageTitle: "Кітапхана",
    libraryFiltersSection: "Сүзгі мен сұрыптау",
    libraryFiltersToggleAria: "Сүзгі мен сұрыптау",
    librarySortDate: "Жүктелген күні бойынша",
    librarySortAlpha: "Әліпби бойынша",
    librarySortLabel: "Сұрыптау",
    libraryFilterKeyword: "Кілт сөздер",
    libraryFilterFrom: "Жүктелген бастап",
    libraryFilterTo: "Жүктелген дейін",
    librarySubmit: "Қолдану",
    libraryEmpty: "Шарттар бойынша кітап жоқ.",
    readOnline: "Онлайн оқу",
    download: "Жүктеу",
    notAvailableLang: "Бұл тілде әлі файл жоқ.",
    scriptureEditionMain: "Негізгі нұсқа",
    scripturePickLanguage: "Нұсқа тілін таңдаңыз",
    scriptureNoLinkForEdition: "Бұл нұсқа үшін сілтеме жоқ",
    scripturePrimaryBadge: "негізгі нұсқа",
    scripturePrimaryOnSite: "Сайттағы негізгі нұсқа",
    scripturePrimaryLegacyNote:
      "Негізгі нұсқаның тілін әкімшілікте көрсетіңіз: кітапты ашып, «Негізгі нұсқа тілі» өрісін толтырыңыз.",
    langNativeRu: "Орысша",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "Ағылшын",
    telegramTitle: "Telegram хабарламалары",
    telegramEmpty: "Хабарламалар әлі жоқ.",
    contacts: "Байланыс",
    address: "Мекенжай",
    historyPageTitle: "Шіркеу тарихы",
    openNews: "Жаңалықты ашу",
    siteLangSelectAria: "Сайт тілі",
  },
  en: {
    parishName: "Greek Catholic parish",
    city: "Almaty",
    navHome: "Home",
    navNews: "News",
    navLibrary: "Library",
    navTelegram: "Telegram",
    navHistory: "History",
    openCalendar: "Liturgical calendar",
    closeModal: "Close",
    imageLightboxAria: "Image preview",
    newsFilters: "Filters",
    todayFeast: "Calendar",
    noFeast: "There is no major feast listed for today.",
    prayer: "Prayer",
    newsTitle: "Parish news",
    filterKeyword: "Keywords",
    filterFrom: "From",
    filterTo: "To",
    resetFilters: "Reset",
    noNews: "No news yet.",
    calendarTitle: "Liturgical calendar",
    calendarHint: "Click a day or event to read details and rules.",
    scriptureTitle: "Useful books",
    scriptureHint: "Read and download online in your chosen language.",
    moreDetails: "Details",
    paginationPrev: "Previous",
    paginationNext: "Next",
    paginationPageOf: "Page {n} of {m}",
    calendarPrevMonth: "Previous month",
    calendarNextMonth: "Next month",
    libraryPageTitle: "Library",
    libraryFiltersSection: "Filters and sorting",
    libraryFiltersToggleAria: "Filters and sorting",
    librarySortDate: "Upload date",
    librarySortAlpha: "Alphabetical",
    librarySortLabel: "Sort",
    libraryFilterKeyword: "Keywords",
    libraryFilterFrom: "Uploaded from",
    libraryFilterTo: "Uploaded to",
    librarySubmit: "Apply",
    libraryEmpty: "No books match these filters.",
    readOnline: "Read online",
    download: "Download",
    notAvailableLang: "No file for this language yet.",
    scriptureEditionMain: "Default edition",
    scripturePickLanguage: "Choose edition language",
    scriptureNoLinkForEdition: "No link for this edition",
    scripturePrimaryBadge: "primary edition",
    scripturePrimaryOnSite: "Primary edition on the site",
    scripturePrimaryLegacyNote:
      "Set the primary edition language in the admin: open the book and use the “Primary language” field.",
    langNativeRu: "Russian",
    langNativeUk: "Ukrainian",
    langNativeKk: "Kazakh",
    langNativeEn: "English",
    telegramTitle: "Telegram messages",
    telegramEmpty: "No messages yet.",
    contacts: "Contacts",
    address: "Address",
    historyPageTitle: "Church history",
    openNews: "Open article",
    siteLangSelectAria: "Site language",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type UiKey = keyof (typeof ui)["ru"];

export function t(lang: Lang, key: UiKey): string {
  return ui[lang][key] ?? ui.ru[key];
}
