import type { Lang } from "./i18n";

export const ui = {
  ru: {
    parishName: "Греко-католический приход Блаженного Алексия Зарицкого",
    parishNameAbbrev: "ГКПБАЗ",
    city: "Алматы",
    navHome: "Главная",
    navLibrary: "Библиотека",
    navAboutChurch: "О церкви",
    aboutChurchPageTitle: "О церкви",
    aboutChurchIntro: "Выберите раздел.",
    aboutNavHierarchy: "Иерархия",
    aboutNavHistory: "История",
    aboutNavContacts: "Наши контакты",
    aboutNavKazakhstanParishes: "Приходы Казахстана",
    kazakhstanParishesPageTitle: "Приходы Казахстана",
    kazakhstanParishesEmpty:
      "Здесь будет список приходов. Записи добавляются в админке и сразу видны на сайте.",
    parishCardWebsite: "Сайт",
    parishCardPriest: "Настоятель",
    hierarchyPageTitle: "Иерархия",
    hierarchyPageIntro: "Священнослужители греко-католического прихода.",
    hierarchyPageEmpty:
      "Список священнослужителей пока не заполнен. Его можно добавить в разделе «Священнослужители» в админке.",
    mapSectionTitle: "Карта",
    mapEmbedTitle: "Местоположение прихода на карте",
    openCalendar: "Открыть календарь на выбранную дату",
    closeModal: "Закрыть",
    imageLightboxAria: "Просмотр изображения",
    newsFilters: "Фильтры",
    todayFeast: "Календарь",
    noFeast: "Сегодня нет никаких событий.",
    prayer: "Молитва",
    newsTitle: "Новости прихода",
    filterKeyword: "Ключевые слова",
    filterFrom: "С даты",
    filterTo: "По дату",
    resetFilters: "Сбросить",
    noNews: "Новостей пока нет.",
    calendarTitle: "Календарь",
    calendarHint: "Нажмите на день или событие, чтобы прочитать пояснение.",
    scriptureTitle: "Полезные книги",
    scriptureHint: "Читайте онлайн и скачивайте на выбранном языке.",
    scriptureShowBooks: "Показать книги",
    scriptureHideBooks: "Скрыть книги",
    moreDetails: "Подробнее",
    paginationPrev: "Назад",
    paginationNext: "Вперёд",
    paginationPageOf: "Стр. {n} из {m}",
    calendarPrevMonth: "Предыдущий месяц",
    calendarNextMonth: "Следующий месяц",
    libraryPageTitle: "Библиотека",
    libraryFiltersSection: "Фильтры и сортировка",
    libraryFiltersToggleAria: "Фильтры и сортировка",
    librarySortDate: "По дате загрузки",
    librarySortAlpha: "По алфавиту",
    librarySortLabel: "Сортировка",
    libraryFilterKeyword: "Ключевые слова",
    libraryFilterFrom: "Загружено с",
    libraryFilterTo: "Загружено по",
    librarySubmit: "Применить",
    libraryEmpty: "Нет книг по заданным условиям.",
    readOnline: "Читать онлайн",
    download: "Скачать",
    notAvailableLang: "Для этого языка файл пока не добавлен.",
    scriptureEditionMain: "Основная версия",
    scripturePickLanguage: "Выберите язык версии",
    scriptureNoLinkForEdition: "Нет ссылки для этой версии",
    scripturePrimaryBadge: "основная версия",
    scripturePrimaryOnSite: "Основная версия на сайте",
    scripturePrimaryLegacyNote:
      "Укажите язык основной версии в админке: откройте книгу и выберите язык в поле «Язык основной версии».",
    langNativeRu: "Русский",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "English",
    telegramTitle: "Сообщения из Telegram",
    telegramEmpty: "Сообщений пока нет.",
    externalLiturgicalWidgetIframeTitle: "Встроенный календарь (prayer-service.pp.ua)",
    contacts: "Контакты",
    address: "Адрес",
    historyPageTitle: "История Церкви",
    openNews: "Открыть новость",
    siteLangSelectAria: "Язык сайта",
    navMainMenuAria: "Главное меню",
  },
  uk: {
    parishName: "Греко-католицька парафія блаженного Олексія Зарицького",
    parishNameAbbrev: "ГКПБОЗ",
    city: "Алмати",
    navHome: "Головна",
    navLibrary: "Бібліотека",
    navAboutChurch: "Про церкву",
    aboutChurchPageTitle: "Про церкву",
    aboutChurchIntro: "Оберіть розділ.",
    aboutNavHierarchy: "Ієрархія",
    aboutNavHistory: "Історія",
    aboutNavContacts: "Наші контакти",
    aboutNavKazakhstanParishes: "Парафії Казахстану",
    kazakhstanParishesPageTitle: "Парафії Казахстану",
    kazakhstanParishesEmpty:
      "Тут з’явиться список парафій. Записи додаються в адмінці й одразу видно на сайті.",
    parishCardWebsite: "Сайт",
    parishCardPriest: "Настоятель",
    hierarchyPageTitle: "Ієрархія",
    hierarchyPageIntro: "Священнослужителі греко-католицької парафії.",
    hierarchyPageEmpty:
      "Список священнослужителів ще не заповнений. Його можна додати в адмінці в розділі «Духовенство».",
    mapSectionTitle: "Мапа",
    mapEmbedTitle: "Розташування парафії на карті",
    openCalendar: "Відкрити календар на обрану дату",
    closeModal: "Закрити",
    imageLightboxAria: "Перегляд зображення",
    newsFilters: "Фільтри",
    todayFeast: "Календар",
    noFeast: "Сьогодні немає жодних подій.",
    prayer: "Молитва",
    newsTitle: "Новини парафії",
    filterKeyword: "Ключові слова",
    filterFrom: "Від дати",
    filterTo: "До дати",
    resetFilters: "Скинути",
    noNews: "Новин ще немає.",
    calendarTitle: "Календар",
    calendarHint: "Натисніть на день або подію, щоб прочитати пояснення.",
    scriptureTitle: "Корисні книги",
    scriptureHint: "Читайте онлайн і завантажуйте обраною мовою.",
    scriptureShowBooks: "Показати книги",
    scriptureHideBooks: "Сховати книги",
    moreDetails: "Докладніше",
    paginationPrev: "Назад",
    paginationNext: "Далі",
    paginationPageOf: "Стор. {n} з {m}",
    calendarPrevMonth: "Попередній місяць",
    calendarNextMonth: "Наступний місяць",
    libraryPageTitle: "Бібліотека",
    libraryFiltersSection: "Фільтри та сортування",
    libraryFiltersToggleAria: "Фільтри та сортування",
    librarySortDate: "За датою завантаження",
    librarySortAlpha: "За абеткою",
    librarySortLabel: "Сортування",
    libraryFilterKeyword: "Ключові слова",
    libraryFilterFrom: "Завантажено від",
    libraryFilterTo: "Завантажено до",
    librarySubmit: "Застосувати",
    libraryEmpty: "Немає книг за цими умовами.",
    readOnline: "Читати онлайн",
    download: "Завантажити",
    notAvailableLang: "Для цієї мови файл ще не додано.",
    scriptureEditionMain: "Основна версія",
    scripturePickLanguage: "Оберіть мову версії",
    scriptureNoLinkForEdition: "Немає посилання для цієї версії",
    scripturePrimaryBadge: "основна версія",
    scripturePrimaryOnSite: "Основна версія на сайті",
    scripturePrimaryLegacyNote:
      "Вкажіть мову основної версії в адмінці: відкрийте книгу та оберіть мову в полі «Мова основної версії».",
    langNativeRu: "Російська",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "Англійська",
    telegramTitle: "Повідомлення з Telegram",
    telegramEmpty: "Повідомлень ще немає.",
    externalLiturgicalWidgetIframeTitle: "Вбудований календар (prayer-service.pp.ua)",
    contacts: "Контакти",
    address: "Адреса",
    historyPageTitle: "Історія Церкви",
    openNews: "Відкрити новину",
    siteLangSelectAria: "Мова сайту",
    navMainMenuAria: "Головне меню",
  },
  kk: {
    parishName: "Блаженді Алексий Зарицкийдің грек-католик қауымы",
    parishNameAbbrev: "ГКҚ БАЗ",
    city: "Алматы",
    navHome: "Басты бет",
    navLibrary: "Кітапхана",
    navAboutChurch: "Шіркеу туралы",
    aboutChurchPageTitle: "Шіркеу туралы",
    aboutChurchIntro: "Бөлімді таңдаңыз.",
    aboutNavHierarchy: "Иерархия",
    aboutNavHistory: "Тарих",
    aboutNavContacts: "Біздің байланыстар",
    aboutNavKazakhstanParishes: "Қазақстан қауымдары",
    kazakhstanParishesPageTitle: "Қазақстан қауымдары",
    kazakhstanParishesEmpty:
      "Қауымдар тізімі әкімшілікте қосылғаннан кейін дереу осы жерде көрінеді.",
    parishCardWebsite: "Сайт",
    parishCardPriest: "Бас священник",
    hierarchyPageTitle: "Иерархия",
    hierarchyPageIntro: "Грек-католик қауымының дін қызметкерлері.",
    hierarchyPageEmpty:
      "Дін қызметкерлер тізімі әлі толтырылмаған. Оны әкімшіліктегі «Дін қызметкерлері» бөлімінен қосуға болады.",
    mapSectionTitle: "Картадағы орналасу",
    mapEmbedTitle: "Қауымның карттағы орны",
    openCalendar: "Таңдалған күнге күнтізбені ашу",
    closeModal: "Жабу",
    imageLightboxAria: "Суретті көру",
    newsFilters: "Сүзгілер",
    todayFeast: "Күнтізбе",
    noFeast: "Бүгін ешқандай оқиға жоқ.",
    prayer: "Дұға",
    newsTitle: "Қауым жаңалықтары",
    filterKeyword: "Кілт сөздер",
    filterFrom: "Бастап",
    filterTo: "Дейін",
    resetFilters: "Тазалау",
    noNews: "Жаңалық жоқ.",
    calendarTitle: "Күнтізбе",
    calendarHint: "Түсіндірме үшін күнге немесе оқиғаға басыңыз.",
    scriptureTitle: "Пайдалы кітаптар",
    scriptureHint: "Онлайн оқыңыз және таңдалған тілде жүктеп алыңыз.",
    scriptureShowBooks: "Кітаптарды көрсету",
    scriptureHideBooks: "Жасыру",
    moreDetails: "Толығырақ",
    paginationPrev: "Артқа",
    paginationNext: "Алға",
    paginationPageOf: "Бет {n} / {m}",
    calendarPrevMonth: "Алдыңғы ай",
    calendarNextMonth: "Келесі ай",
    libraryPageTitle: "Кітапхана",
    libraryFiltersSection: "Сүзгі мен сұрыптау",
    libraryFiltersToggleAria: "Сүзгі мен сұрыптау",
    librarySortDate: "Жүктелген күні бойынша",
    librarySortAlpha: "Әліпби бойынша",
    librarySortLabel: "Сұрыптау",
    libraryFilterKeyword: "Кілт сөздер",
    libraryFilterFrom: "Жүктелген бастап",
    libraryFilterTo: "Жүктелген дейін",
    librarySubmit: "Қолдану",
    libraryEmpty: "Шарттар бойынша кітап жоқ.",
    readOnline: "Онлайн оқу",
    download: "Жүктеу",
    notAvailableLang: "Бұл тілде әлі файл жоқ.",
    scriptureEditionMain: "Негізгі нұсқа",
    scripturePickLanguage: "Нұсқа тілін таңдаңыз",
    scriptureNoLinkForEdition: "Бұл нұсқа үшін сілтеме жоқ",
    scripturePrimaryBadge: "негізгі нұсқа",
    scripturePrimaryOnSite: "Сайттағы негізгі нұсқа",
    scripturePrimaryLegacyNote:
      "Негізгі нұсқаның тілін әкімшілікте көрсетіңіз: кітапты ашып, «Негізгі нұсқа тілі» өрісін толтырыңыз.",
    langNativeRu: "Орысша",
    langNativeUk: "Українська",
    langNativeKk: "Қазақша",
    langNativeEn: "Ағылшын",
    telegramTitle: "Telegram хабарламалары",
    telegramEmpty: "Хабарламалар әлі жоқ.",
    externalLiturgicalWidgetIframeTitle: "Кірістірілген күнтізбе (prayer-service.pp.ua)",
    contacts: "Байланыс",
    address: "Мекенжай",
    historyPageTitle: "Шіркеу тарихы",
    openNews: "Жаңалықты ашу",
    siteLangSelectAria: "Сайт тілі",
    navMainMenuAria: "Негізгі мәзір",
  },
  en: {
    parishName: "Greek Catholic parish of Blessed Oleksiy Zarytsky",
    parishNameAbbrev: "GCP BAZ",
    city: "Almaty",
    navHome: "Home",
    navLibrary: "Library",
    navAboutChurch: "About the parish",
    aboutChurchPageTitle: "About the parish",
    aboutChurchIntro: "Choose a section.",
    aboutNavHierarchy: "Hierarchy",
    aboutNavHistory: "History",
    aboutNavContacts: "Our contacts",
    aboutNavKazakhstanParishes: "Parishes in Kazakhstan",
    kazakhstanParishesPageTitle: "Parishes in Kazakhstan",
    kazakhstanParishesEmpty:
      "Parishes appear here as soon as they are added in the admin.",
    parishCardWebsite: "Website",
    parishCardPriest: "Rector",
    hierarchyPageTitle: "Hierarchy",
    hierarchyPageIntro: "Clergy of the Greek Catholic parish.",
    hierarchyPageEmpty:
      "No clergy entries yet. Add them in the admin under “Clergy”.",
    mapSectionTitle: "Map",
    mapEmbedTitle: "Parish location on the map",
    openCalendar: "Open calendar for the selected date",
    closeModal: "Close",
    imageLightboxAria: "Image preview",
    newsFilters: "Filters",
    todayFeast: "Calendar",
    noFeast: "There are no events today.",
    prayer: "Prayer",
    newsTitle: "Parish news",
    filterKeyword: "Keywords",
    filterFrom: "From",
    filterTo: "To",
    resetFilters: "Reset",
    noNews: "No news yet.",
    calendarTitle: "Calendar",
    calendarHint: "Click a day or event to read details and rules.",
    scriptureTitle: "Useful books",
    scriptureHint: "Read and download online in your chosen language.",
    scriptureShowBooks: "Show books",
    scriptureHideBooks: "Hide books",
    moreDetails: "Details",
    paginationPrev: "Previous",
    paginationNext: "Next",
    paginationPageOf: "Page {n} of {m}",
    calendarPrevMonth: "Previous month",
    calendarNextMonth: "Next month",
    libraryPageTitle: "Library",
    libraryFiltersSection: "Filters and sorting",
    libraryFiltersToggleAria: "Filters and sorting",
    librarySortDate: "Upload date",
    librarySortAlpha: "Alphabetical",
    librarySortLabel: "Sort",
    libraryFilterKeyword: "Keywords",
    libraryFilterFrom: "Uploaded from",
    libraryFilterTo: "Uploaded to",
    librarySubmit: "Apply",
    libraryEmpty: "No books match these filters.",
    readOnline: "Read online",
    download: "Download",
    notAvailableLang: "No file for this language yet.",
    scriptureEditionMain: "Default edition",
    scripturePickLanguage: "Choose edition language",
    scriptureNoLinkForEdition: "No link for this edition",
    scripturePrimaryBadge: "primary edition",
    scripturePrimaryOnSite: "Primary edition on the site",
    scripturePrimaryLegacyNote:
      "Set the primary edition language in the admin: open the book and use the “Primary language” field.",
    langNativeRu: "Russian",
    langNativeUk: "Ukrainian",
    langNativeKk: "Kazakh",
    langNativeEn: "English",
    telegramTitle: "Telegram messages",
    telegramEmpty: "No messages yet.",
    externalLiturgicalWidgetIframeTitle: "Embedded liturgical calendar (prayer-service.pp.ua)",
    contacts: "Contacts",
    address: "Address",
    historyPageTitle: "Church history",
    openNews: "Open article",
    siteLangSelectAria: "Site language",
    navMainMenuAria: "Main menu",
  },
} as const satisfies Record<Lang, Record<string, string>>;

export type UiKey = keyof (typeof ui)["ru"];

export function t(lang: Lang, key: UiKey): string {
  return ui[lang][key] ?? ui.ru[key];
}
